---

 # docker integration
  - name: Add dd-agent to docker group
    user: name=dd-agent groups=docker append=yes
    notify:
    - restart datadog

  - name: Install docker condfig
    template: src=conf.d/docker.yaml dest=/etc/dd-agent/conf.d/docker.yaml
    notify:
     - restart datadog